#+HTML_HEAD: <meta charset="utf-8">
#+HTML_HEAD: <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="others.css">
#+OPTIONS: toc:nil num:nil html-postamble:nil
#+TITLE: Digimon - digikar99.github.io

#+BEGIN_CENTER
[[file:index.html#home][Home]] | [[file:common-lisp-and-emacs.html][Common Lisp and Emacs]] | [[file:agi-cogsci.html][AGI and Cognitive Science]] | *DIGIMON*
#+END_CENTER

#+html: <br>

#+begin_quote
For some reason, it seems I have slightly moved on from Digimon. 

A big part of it perhaps has to do with the lingering question of what should (school) education look like. When I had written the below article in 2021, I was still somewhat enthusiastic about school education, about gathering resources about certain kinds of basic knowledge that every human - and perhaps every sentient being - should know for a better world.

But it seems the more I thought about that, the more I realized that determining such kinds of basic knowledge depends on the position one takes about how a society or civilization should operate. There are basic themes of Utilitarianism and of Sustainability, but the detailing remains to be worked out. Lacking that detail, I seem to have entered a state of apathy for things beyond my immediate whims and goals.
#+end_quote

I'd strongly urge the reader to get young, as young as 10 or 12, and re-grow with the characters in [[https://human9being9.wordpress.com/digimon/the-depths-of-adventures/][Digimon Adventure (1999)]]. It is by no means perfect but definitely leaves some valuable marks on the viewer. Some of the things,

**Digimon Adventure tri.**

- There are things you can see when you're young, but can't when you grow up. In reverse, there are things that you see as an adult that you never noticed as a child. But what is it that you're supposed to see, and what you're not?
- Hikari was saying earlier that if it doesn't occur around us, we can't understand. In the end, I wonder if it is even possible to share the same feelings.
- Isn't it scary? We can never understand how serious a matter is unless it actually occurs around us.
- When I'm hungry, I always eat something. Taichi, you should do exactly what you want to do.
- No matter how difficult it is, you have to make a decision sometimes. Even if you're up against a friend.
- Knowing nothing is just a chance to learn new things.
- Acting on the basis of good intentions alone isn't enough.
- I don't like holding myself back for the sake of others. Being quiet in front of people means you're just complaining later. When people have something to say they should just speak up. (But don't be a /jikochu/ either!)

**Digimon Adventures 02**

- Being a great human hasn't got anything to do with being envied. 	It's only measured by how much we can contribute to others.
- You must be more troubled. You must suffer more. Because that's what it means to live. Even if you feel miserable and don't want anyone to see you, you have to go on.
- Erasing darkness completely may be impossible, for where there's light, there's darkness; that's why don't lose sight of the light inside you, however dark it may be. Light gives life to this world; hope means not to lose the light even when engulfed by darkness
- In people's heart as well as the world, there is light and darkness. They will continue to battle each other forever. However, as long as you keep the light in your heart and hold the power to realize your dreams, all will be fine. Those who will turn the pages of new adventures are you.
- If we try hard enough, we'll be able to do something. If we all work together, there's nothing we can't do.
- We have to grab our future with our own hands [for our dream to come true].
- Is it okay to be stuck in the past [when you have things to do now]?
- There is a reason behind every being's existence, that only that being can find out.

**Digimon Adventures**

- You are the only ones who can save the world.
- There aren't many quotes in Digimon Adventures, but even then, the character development is amazing!

* Other Anime

Anime are often famous for being "profound". During my undergrad years, I had the liberty to watch Naruto and Fullmetal Alchemist: Brotherhood. Masterpieces in themselves. If anything, I've developed much nostalgia for FMAB. Yet, neither could displace my regard for Digimon Adventure (1999).

To me, it doesn't feel like I'm blinded by nostalgia towards Digimon Adventure (1999). There certainly is nostalgia, but (i) the nostalgia is rather recent (ii) there's more to it than nostalgia. My childhood love was rather Pokemon and Beyblade for a good while. Before 14, I think I have spent more time with them than with Digimon. So, clearly, I should be rather nostalgic towards them than with Digimon. Heck, as far as I can recall, my nostalgia with Digimon only began after I turned 14, while I was beginning to come to terms with emotions and becoming-a-half-adult.

If anything, I also cooked up a comparison between [[https://drive.google.com/file/d/1ES81Livx-_Rst0zoxAMXC-crsQk4Jk_y/view?usp=sharing][Digimon Adventure (1999) and Naruto]] some time in 2018; I haven't been able to wrap my head very well around the differences; to me,
- Digimon seems to give off a "me collaborating aka not playing tricks with /us/ and giving to the world at large" vibes
- while Naruto seems to give off (a more grounded perhaps?) "me, the friends who accepted and believed in me, my family, the community /vs/ the tragedies of life and how I climb up the social ladder".

If or not this is the difference if there is one at all, would surely constitute an interesting discussion /if and when I find the time/. If interested, feel free to ping me up at shubhamayare[at]yahoo[dot]co[dot]in!
